import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import { prisma } from "@/lib/prisma";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function trackVisit() {
  try {
    const d = new Date();
    const year = d.getFullYear();
    const month = String(d.getMonth() + 1).padStart(2, "0");
    const day = String(d.getDate()).padStart(2, "0");
    const todayStr = `${year}-${month}-${day}`;
    const dailyKey = `visit_date:${todayStr}`;

    // Update total count
    const totalRecord = await prisma.setting.findUnique({ where: { key: "visitor_count" } });
    const totalCount = totalRecord ? parseInt(totalRecord.value, 10) : 0;
    const nextTotal = isNaN(totalCount) ? 1 : totalCount + 1;
    await prisma.setting.upsert({
      where: { key: "visitor_count" },
      update: { value: String(nextTotal) },
      create: { key: "visitor_count", value: String(nextTotal) }
    });

    // Update daily count
    const dailyRecord = await prisma.setting.findUnique({ where: { key: dailyKey } });
    const dailyCount = dailyRecord ? parseInt(dailyRecord.value, 10) : 0;
    const nextDaily = isNaN(dailyCount) ? 1 : dailyCount + 1;
    await prisma.setting.upsert({
      where: { key: dailyKey },
      update: { value: String(nextDaily) },
      create: { key: dailyKey, value: String(nextDaily) }
    });
  } catch (error) {
    console.error("Failed to track visit:", error);
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await trackVisit();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="min-h-screen bg-[#f7f4ee] text-slate-900">
          <Header />
          <main>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
